#!/usr/bin/env node
/*-*- mode: Javascript; -*-*/

var fs = require('fs')
$ = require('jquery');
var _ = require('underscore');
var boosd = require('./engine.js');

dataStore = {};
dataStore.getFile = function(path, cb) {
    fs.readFile('test/data/lynx-hares2.xml', function(err, data) {
        cb(err, data);
    });
}

require.paths.push(__dirname);

var reporter = require('nodeunit').reporters.default;

process.chdir(__dirname);
reporter.run(['test']);

