export declare function titleCase(str: string): string;
export declare function dName(s: string): string;
export declare function eName(s: string): string;
export declare function set(...args: string[]): any;
export declare function partition(array: any[], l: number, r: number, p: number): number;
export declare function sort(array: any[], l?: number, r?: number, part?: typeof partition): void;
export declare function lookup(table: any, index: number): number;
export declare function min(a: number, b: number): number;
export declare function numArr(arr: any[]): number[];
export declare function floatAttr(o: any, n: any): number;
export declare function qs(e: any, s: any): any;
export declare function querySelectorInner(e: any, selectors: any): any;
export declare function qsa(e: any, s: any): any;
export declare function isNaN(n: number): boolean;
export declare function camelCase(s: string): string;
export declare function splitOnComma(str: string): string[];
export declare function numberize(arr: string[]): number[];
export declare function i32(n: number): number;
